---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: triton-server-yolov8
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    build: triton-server
spec:
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/redhat-na-ssa/demo-computer-vision.git
      ref: main
    contextDir: examples/yolov8
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: triton-server:latest
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: triton:latest
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: ultralytics:latest
