---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: triton-builder
spec:
  lookupPolicy:
    local: true
  tags:
  - name: latest
