---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-triton
  labels:
    component: demo-triton
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops
    repoURL: >-
      https://github.com/codekow/s2i-triton
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
