---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  source: https://github.com/redhat-na-ssa/demo-computer-vision.git

labels:
- includeSelectors: false
  pairs:
    demo: computer-vision

resources:
- overlays/default
